"""
고객 맞춤형 출력 템플릿 엔진
사용자가 원하는 출력 형식을 자유롭게 정의할 수 있는 시스템
"""

import json
import logging
from typing import Dict, List, Any, Optional
from pathlib import Path
from jinja2 import Template, Environment, FileSystemLoader, select_autoescape

logger = logging.getLogger(__name__)


class OutputTemplate:
    """출력 템플릿 정의"""

    def __init__(self, template_id: str, name: str, description: str, template_content: str):
        self.template_id = template_id
        self.name = name
        self.description = description
        self.template_content = template_content

    def render(self, data: Dict[str, Any]) -> str:
        """템플릿 렌더링"""
        try:
            template = Template(self.template_content)
            return template.render(**data)
        except Exception as e:
            logger.error(f"템플릿 렌더링 실패: {str(e)}", exc_info=True)
            return f"<!-- 렌더링 오류: {str(e)} -->"


class TemplateEngine:
    """고객 맞춤형 템플릿 엔진"""

    def __init__(self, templates_dir: str = "templates"):
        self.templates_dir = Path(templates_dir)
        self.templates_dir.mkdir(exist_ok=True)

        # 내장 템플릿 (기본 제공)
        self.builtin_templates = self._create_builtin_templates()

        # 사용자 정의 템플릿 로드
        self.custom_templates = self._load_custom_templates()

        logger.info(f"템플릿 엔진 초기화: {len(self.builtin_templates)} 내장 + {len(self.custom_templates)} 커스텀")

    def _create_builtin_templates(self) -> Dict[str, OutputTemplate]:
        """내장 템플릿 생성"""
        templates = {}

        # 1. 모바일 최적화 HTML (기본)
        templates['mobile_html'] = OutputTemplate(
            template_id='mobile_html',
            name='모바일 최적화 HTML',
            description='반응형 디자인의 모바일 친화적 HTML',
            template_content="""
<!DOCTYPE html>
<html lang="{{ language|default('ko') }}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <style>
        body { font-family: -apple-system, sans-serif; margin: 0; padding: 20px; }
        .content { max-width: 800px; margin: 0 auto; }
        h1 { color: #333; }
        p { line-height: 1.6; }
    </style>
</head>
<body>
    <div class="content">
        <h1>{{ title }}</h1>
        {{ content | safe }}
    </div>
</body>
</html>
            """
        )

        # 2. JSON 출력
        templates['json'] = OutputTemplate(
            template_id='json',
            name='JSON 형식',
            description='API 연동용 JSON 데이터',
            template_content='{{ data | tojson(indent=2) }}'
        )

        # 3. Markdown 출력
        templates['markdown'] = OutputTemplate(
            template_id='markdown',
            name='Markdown',
            description='마크다운 형식의 텍스트',
            template_content="""
# {{ title }}

{{ content }}

---
Generated by StudySnap
            """
        )

        # 4. 프린트용 HTML
        templates['print_html'] = OutputTemplate(
            template_id='print_html',
            name='프린트용 HTML',
            description='A4 용지 출력 최적화 HTML',
            template_content="""
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        @media print {
            @page { size: A4; margin: 2cm; }
            body { font-size: 12pt; }
        }
        body { font-family: 'Malgun Gothic', sans-serif; }
        h1 { page-break-after: avoid; }
        .page-break { page-break-after: always; }
    </style>
</head>
<body>
    <h1>{{ title }}</h1>
    {{ content | safe }}
</body>
</html>
            """
        )

        # 5. 프레젠테이션 HTML
        templates['presentation'] = OutputTemplate(
            template_id='presentation',
            name='프레젠테이션',
            description='발표용 슬라이드 형식',
            template_content="""
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        .slide {
            width: 100vw;
            height: 100vh;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            page-break-after: always;
        }
        h1 { font-size: 3em; }
        p { font-size: 1.5em; }
    </style>
</head>
<body>
    {% for page in pages %}
    <div class="slide">
        <h1>{{ page.title }}</h1>
        <p>{{ page.content }}</p>
    </div>
    {% endfor %}
</body>
</html>
            """
        )

        # 6. 이메일 템플릿
        templates['email'] = OutputTemplate(
            template_id='email',
            name='이메일',
            description='이메일 전송용 HTML',
            template_content="""
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        body { font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; }
        .header { background: #4CAF50; color: white; padding: 20px; text-align: center; }
        .content { padding: 20px; }
        .footer { background: #f1f1f1; padding: 10px; text-align: center; font-size: 12px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ title }}</h1>
    </div>
    <div class="content">
        {{ content | safe }}
    </div>
    <div class="footer">
        Powered by StudySnap
    </div>
</body>
</html>
            """
        )

        # 7. 테이블 중심 레이아웃
        templates['table_layout'] = OutputTemplate(
            template_id='table_layout',
            name='테이블 레이아웃',
            description='데이터 테이블 중심의 레이아웃',
            template_content="""
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        table { width: 100%; border-collapse: collapse; margin: 20px 0; }
        th, td { border: 1px solid #ddd; padding: 12px; text-align: left; }
        th { background-color: #4CAF50; color: white; }
        tr:nth-child(even) { background-color: #f2f2f2; }
    </style>
</head>
<body>
    <h1>{{ title }}</h1>
    {{ content | safe }}
</body>
</html>
            """
        )

        return templates

    def _load_custom_templates(self) -> Dict[str, OutputTemplate]:
        """사용자 정의 템플릿 로드"""
        custom_templates = {}

        templates_file = self.templates_dir / "custom_templates.json"
        if templates_file.exists():
            try:
                with open(templates_file, 'r', encoding='utf-8') as f:
                    data = json.load(f)
                    for template_data in data.get('templates', []):
                        template = OutputTemplate(**template_data)
                        custom_templates[template.template_id] = template
                        logger.info(f"커스텀 템플릿 로드: {template.name}")
            except Exception as e:
                logger.error(f"커스텀 템플릿 로드 실패: {str(e)}")

        return custom_templates

    def get_template(self, template_id: str) -> Optional[OutputTemplate]:
        """템플릿 ID로 템플릿 가져오기"""
        # 커스텀 템플릿 우선
        if template_id in self.custom_templates:
            return self.custom_templates[template_id]

        # 내장 템플릿
        if template_id in self.builtin_templates:
            return self.builtin_templates[template_id]

        logger.warning(f"템플릿을 찾을 수 없음: {template_id}")
        return None

    def list_templates(self) -> List[Dict[str, str]]:
        """사용 가능한 모든 템플릿 목록"""
        templates = []

        # 내장 템플릿
        for template in self.builtin_templates.values():
            templates.append({
                'id': template.template_id,
                'name': template.name,
                'description': template.description,
                'type': 'builtin'
            })

        # 커스텀 템플릿
        for template in self.custom_templates.values():
            templates.append({
                'id': template.template_id,
                'name': template.name,
                'description': template.description,
                'type': 'custom'
            })

        return templates

    def create_custom_template(self, template_id: str, name: str, description: str,
                               template_content: str) -> bool:
        """새로운 커스텀 템플릿 생성"""
        try:
            # 유효성 검사
            Template(template_content)  # Jinja2 문법 검증

            template = OutputTemplate(template_id, name, description, template_content)
            self.custom_templates[template_id] = template

            # 저장
            self._save_custom_templates()
            logger.info(f"커스텀 템플릿 생성: {name}")
            return True

        except Exception as e:
            logger.error(f"커스텀 템플릿 생성 실패: {str(e)}", exc_info=True)
            return False

    def _save_custom_templates(self):
        """커스텀 템플릿 저장"""
        templates_file = self.templates_dir / "custom_templates.json"
        try:
            data = {
                'templates': [
                    {
                        'template_id': t.template_id,
                        'name': t.name,
                        'description': t.description,
                        'template_content': t.template_content
                    }
                    for t in self.custom_templates.values()
                ]
            }

            with open(templates_file, 'w', encoding='utf-8') as f:
                json.dump(data, f, ensure_ascii=False, indent=2)

        except Exception as e:
            logger.error(f"커스텀 템플릿 저장 실패: {str(e)}")

    def render(self, template_id: str, data: Dict[str, Any]) -> Optional[str]:
        """템플릿 렌더링"""
        template = self.get_template(template_id)
        if template:
            return template.render(data)
        return None


# 싱글톤 인스턴스
_template_engine = None

def get_template_engine() -> TemplateEngine:
    """템플릿 엔진 싱글톤 인스턴스"""
    global _template_engine
    if _template_engine is None:
        _template_engine = TemplateEngine()
    return _template_engine
